### ISSUE TITLE
Keyword 'packages' not supported

### ISSUE THREAD

**Issue by AnHeuermann** [AnHeuermann/setup-openmodelica#167]
When running 

```yml
      - name: "Set up OpenModelica"
        uses: AnHeuermann/setup-openmodelica@v0.4
        with:
          version: 'stable'
          packages: |
            omc
```

I get
 
```
Warning: Unexpected input(s) 'packages', valid inputs are ['version', 'architecture']
```
